name: 'coursier-cache-action-test'
description: 'coursier cache action test'
author: 'Alexandre Archambault'
branding:
  icon: 'arrow-down'
  color: 'white'
inputs:
  root:
    required: false
    description: 'root directory containing build tool files'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
