name: 'coursier-cache-action'
description: 'coursier cache action'
author: 'Alexandre Archambault'
inputs:
  root:
    required: false
    description: 'root directory containing build tool files'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
